apiVersion: v1
kind: Template
metadata:
  name: demo-broker
objects:

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: demo-broker-client

- kind: Secret
  apiVersion: v1
  metadata:
    name: demo-broker
    annotations:
      kubernetes.io/service-account.name: demo-broker-client
  type: kubernetes.io/service-account-token

- apiVersion: servicecatalog.k8s.io/v1beta1
  kind: ClusterServiceBroker
  metadata:
    name: demo-broker
  spec:
    url: https://demo-broker.demo-broker.svc.cluster.local
    caBundle: ${BROKER_CA_CERT}
    authInfo:
      bearer:
        secretRef:
          namespace: ${NAMESPACE}
          name: demo-broker

- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: demo-broker

- kind: ClusterRole
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: demo-broker
  rules:
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]

- kind: ClusterRole
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: access-demo-broker
  rules:
  - nonResourceURLs: ["/v2", "/v2/*"]
    verbs: ["GET", "POST", "PUT", "PATCH", "DELETE"]

- kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: demo-broker
  subjects:
    - kind: ServiceAccount
      name: demo-broker
      namespace: ${NAMESPACE}
  roleRef:
    kind: ClusterRole
    name: demo-broker

- kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: demo-broker-client
  subjects:
    - kind: ServiceAccount
      name: demo-broker-client
      namespace: ${NAMESPACE}
  roleRef:
    kind: ClusterRole
    name: access-demo-broker

- kind: Service
  apiVersion: v1
  metadata:
    name: demo-broker
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: 'demo-broker-ssl'
    labels:
      app: demo-broker
  spec:
    selector:
      app: demo-broker
    ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: demo-broker
    labels:
      app: demo-broker
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: demo-broker
    template:
      metadata:
        labels:
          app: demo-broker
      spec:
        serviceAccount: demo-broker
        containers:
        - name: service-demo-broker
          image: ${IMAGE}
          imagePullPolicy: IfNotPresent
          command:
          - /opt/servicebroker/servicebroker
          args:
          - --port
          - "8443"
          - -v
          - "4"
          - --logtostderr
          - --tls-cert-file
          - "/var/run/demo-broker/starterpack.crt"
          - --tls-private-key-file
          - "/var/run/demo-broker/starterpack.key"
          - --authenticate-k8s-token
          - --catalogPath
          - ${CATALOG_PATH}
          ports:
          - containerPort: 8443
          readinessProbe:
            httpGet:
              path: /healthz
              scheme: HTTPS
              port: 8443
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          volumeMounts:
          - mountPath: /var/run/demo-broker
            name: demo-broker-ssl
            readOnly: true
        volumes:
        - name: demo-broker-ssl
          secret:
            defaultMode: 420
            secretName: demo-broker-ssl
            items:
            - key: tls.crt
              path: starterpack.crt
            - key: tls.key
              path: starterpack.key

parameters:
- description: Name of the image to use
  displayName: Image name
  name: IMAGE
  required: true
  value: quay.io/osb-starter-pack/servicebroker:latest

- description: base64 encoded SSL CA Certificate
  displayName: base64 encoded SSL CA Certificate
  name: BROKER_CA_CERT
  required: true
  value:

- description: Namespace that the starter pack is deployed to
  displayName: Namespace
  name: NAMESPACE
  value: demo-broker

- description: URL to a json formated resource that represents the catalog
  displayName: catalogPath
  name: CATALOG_PATH
  value: https://raw.githubusercontent.com/cheld/demo-broker/master/samples/catalog.json
